name: quiz_app
description: A Bible Quiz app by Tosin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-327.0.dev

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/quiz.json
    - assets/icon/app_icon.png

# THIS MUST BE OUTSIDE OF "flutter:"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
